from typing import Any, Dict, List, Optional, Set, Tuple

base_path: str
models_dir: str
folder_names_and_paths: Dict[str, Tuple[List[str], Set[str]]]

def get_output_directory() -> str: ...
def get_input_directory() -> str: ...
def get_temp_directory() -> str: ...
def get_user_directory() -> str: ...
def get_annotated_filepath(name: str) -> str: ...
def get_filename_list(folder_name: str) -> List[str]: ...
def get_full_path(folder_name: str, filename: str) -> Optional[str]: ...
def get_save_image_path(filename_prefix: str, output_dir: str, image_width: int = 0, image_height: int = 0) -> Tuple[str, str, int, str, str]: ...
def filter_files_extensions(files: List[str], extensions: List[str]) -> List[str]: ...
def recursive_search(directory: str, excluded_dir_names: Optional[List[str]] = None) -> Tuple[List[str], Dict[str, float]]: ...
